export const ATTEMPTING = 'ATTEMPTING';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ADDING_POST = 'ADDING_POST';
export const ADDING_SUCCESS = 'ADDING_SUCCESS';
export const ADDING_FAILED = 'ADDING_FAILED';

export const FETCHING = 'FETCHING';
export const FETCHING_DONE = 'FETCHING_DONE';
