export const ATTEMPTING = 'ATTEMPTING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const ADDING_POST = 'ADDING_POST';
export const ADDING_SUCCESS = 'ADDING_SUCCESS';
export const ADDING_FAILED = 'ADDING_FAILED';

export const FETCHING = 'FETCHING';
export const FETCHING_DONE = 'FETCHING_DONE';
